### ISSUE TITLE
Tag master branch

### ISSUE THREAD

**Issue by keviny22** [fnichol/chef-user#41]
Please tag the master branch, the newest tag 3.0 is 11 months old. There are fixes in the current master branch that I need to use and I prefer to use versions rather then sha's in my Berksfile

**Comment by patcon** [comment]
+1

The lack of tags is disrupting a common way that people get community cookbooks into their chef-repo:

```
cd /path/to/cookbooks
git clone fnichol/chef-user user
cd user
git checkout v0.4.2
knife cookbook upload user
```

**Comment by theckman** [comment]
I've been recently added as a collaborator and have pushed `0.5.0` and `0.5.1` to address further bugs that were fixed in `master` and not release. I may try to go back and retroactiveley `git tag` the commits where each version happened.

I plan on trying to keep better tabs on this cookbook to avoid issues like this coming up. I'm going to close this issue. Let us know if you need anything else.
