### ISSUE TITLE
Incorrect action?

### ISSUE THREAD

**Issue by CpuID** [fnichol/chef-user#91]
Should this be unless exec_action == :remove ?

https://github.com/fnichol/chef-user/blob/master/providers/account.rb#L107

**Comment by ranjib** [comment]
yes. its a bug. i'll fix it. thanks for catching it @CpuID .

**Comment by CpuID** [comment]
no problem :)

**Comment by theckman** [comment]
@ranjib @CpuID do you know if this bug was patched? The URL in the issue comment doesn't include the original commit, so the line number has drifted. I assume it was referring to this line:

* https://github.com/fnichol/chef-user/blob/b1a0adaaa0d3b58524e7a677f2713b630441c510/providers/account.rb#L117

**Comment by theckman** [comment]
This should be fixed by cfcdabc.
